[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin"
  to = "/amdin"
  status = 301
  force = true

[[redirects]]
  from = "/amdin"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/amdin/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200